language: node_js
node_js:
  - "7"
services:
  - postgresql
before_script:
  - npm install -g sequelize-cli
  - psql -c 'create database postit;' -U postgres
  - psql -c 'create database postit_test;' -U postgres
script: 
  - npm install
  - npm run test
  - npm run coverage
after_success:
  - npm run coveralls