export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const GET_USER_GROUP = 'GET_USER_GROUP';
export const CREATE_USER_GROUP = 'CREATE_USER_GROUP';
export const GET_GROUP_MESSAGES = 'GET_GROUP_MESSAGES';
export const CREATE_GROUP_MESSAGE = 'CREATE_GROUP_MESSAGE';